<section class='example'>
  <div class='gridly'>
    $orginfo:{
    <div id="D05" class="bedStyle" style="width:150px; height:160px;background: rgb(154, 168, 118);">
      <input class="SerialNum" type="hidden" value="$it.OrgId$" />
      <div style="position: absolute; font-size: 18px; font-weight: bold; left: 8px; top: 20px">$it.OrgName$</div>
      <div style="position: absolute; font-size: 15px; left: 8px; top: 60px; ">楼宇数：$it.BuildNum$</div>
      <div style="position: absolute; font-size: 15px; left: 8px; top: 80px; ">房间数：$it.RoomNum$</div>
      <div style="position: absolute; font-size: 15px; left: 8px; top: 100px; ">床位数：$it.BedNum$</div>
      <div style="position: absolute; font-size: 15px; left: 8px; top: 120px; ">入住率：$it.RateBed$</div>
    </div>
    }$
  </div>
</section>